### ISSUE TITLE
navigatiob bar issue

### ISSUE THREAD

**Issue by gaganpsinghkrishnais** [goktugyil/EZSwipeController#11]
Ass all my view controllers have buttons on then and after passing the View controllers the newly crety view didnt contain their navigation bars included

**Comment by Esqarrouth** [comment]
Can you show screenshots?

**Comment by gaganpsinghkrishnais** [comment]
![screen shot 2016-02-24 at 12 28 17 pm](https://cloud.githubusercontent.com/assets/16206552/13277900/2f31bb70-daf2-11e5-8f79-cb6c84d8a46f.png)
this is the navigation bar show when i use the default navigation function. But as i import views they have their own navigation bars those bars are not displaying.

**Comment by gaganpsinghkrishnais** [comment]
thanks for this awesom library..it was totally my fault that this issue is arriving .....its working perfectly now thanks again...

**Comment by sebyddd** [comment]
@gaganpsinghkrishnais, I know you fixed this but just in case others stumble upon this issue: 

Make sure to embed your EZSwipeController in a UINavigationController.
