### ISSUE TITLE
Pushing to another view controller?

### ISSUE THREAD

**Issue by andrewjedi** [goktugyil/EZSwipeController#13]
Is it possible to push to another view controller not in the stack? Trying to access the main nav bar to do so, but finding it difficult. Thank you!

**Comment by Esqarrouth** [comment]
So its usually

app->ezswipe 
ezswipe->vc1
ezswipe->vc2
ezswipe->vc3

you can make those vc's navigation controllers and make them work like a stack. Is this what you want?

**Comment by andrewjedi** [comment]
I have 4 VC's in the stack, but however on the last VC. I want to push to the "MessagesVC" -- but I do not want it in the stack, because they should only be able to access the MessagesVC if they click on the persons name. I don't want it to be a modal though.

Is this possible at all? I hope this makes sense

**Comment by Esqarrouth** [comment]
app->ezswipe 
ezswipe->vc1
ezswipe->vc2
ezswipe->vc3
ezswipe->navigation controller->vc4->messagesvc

**Comment by andrewjedi** [comment]
See it would be amazing if I could make it push to another VC when they click the users name to chat. But obviously I do not want it in the EZSwipe stack, otherwise they would just be able to swipe to that controller without having to click a username.

Thank you!

<img width="556" alt="screen shot 2016-03-05 at 11 45 35 am" src="https://cloud.githubusercontent.com/assets/7296429/13549999/d2bf618e-e2c7-11e5-9827-5ce987672ad4.png">

**Comment by andrewjedi** [comment]
Is this doable? Thank you!

**Comment by Esqarrouth** [comment]
You can make that with just pushing inside the navigationviewcontroller. Someone already implemented a similar one, I'll let him know.

**Comment by andrewjedi** [comment]
Yea I've been trying :-/ I can't figure it out :(

**Comment by stanchiang** [comment]
you can look into parent/child view controller patterns. i did this before for a similar situation. it's kinda hacky but basically you can just switch to another view controller. 

no idea how that effects memory or vc stack in on a performance basis but it works just fine for me in general.

quick example
https://gist.github.com/tomohisa/2897676

**Comment by andrewjedi** [comment]
Will look into this right now, I will report back :)

**Comment by Esqarrouth** [comment]
I guess this issue is solved

**Comment by gkuhlmann14** [comment]
hey @andrewfashion did you end up figuring this out?

I'm having a similar issue as you, basically when I do what @goktugyil recommended:

app->ezswipe 
ezswipe->vc1
ezswipe->navigation controller->vc2->messagesvc

The nav controller in vc2 isn't using the same nav bar when I push and pop to the nav stack
When I use that design there are TWO nav bars in the view, the top bar is the EZSwipe nav bar and the bottom bar is the nav bar from the navigation controller. When I push and pop the EZSwipe nav bar is stationary and the new vc2 navigation controller bar below it has the back button in the bar. 

The most user friendly functionality from a EZSwipe perspective is to figure out a way to simply push and pop VC's to the stack and the EZSwipe nav bar is used for both main swipe and going down the nav views.

I'm playing around with it now, but I think I'm going to try to hide the EZSwipe nav bar, make my messages VC and Vc1 nav controllers. This will give me the same swipe functionality with custom nav bars.

I'm still working on it this weekend and am around if you can comment.
