### ISSUE TITLE
Programmatically navigating to different pages

### ISSUE THREAD

**Issue by neilsekhon** [goktugyil/EZSwipeController#14]
Is there a way to go to different pages without swiping? I tried this method setViewControllers:direction:animated:completion:
but it crashes.

Thanks, Neil

**Comment by Esqarrouth** [comment]
Did you try looking at the code of the buttons? Or is that not what you want?

**Comment by Esqarrouth** [comment]
http://stackoverflow.com/questions/tagged/ezswipecontroller

You can ask your question here if you want to. If you solved the problem please send a pull request. Thanks!
