### ISSUE TITLE
Implementing Init

### ISSUE THREAD

**Issue by chrisnovello** [goktugyil/EZSwipeController#2]
Hi!  Any reason to leave init?(coder) unimplemented? Would this:

```
public required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
}
```

cause any problems?

**Comment by Esqarrouth** [comment]
Personally not using storyboards to call this. If you are calling from storyboards and there needs to be additions, both in code and readme, feel free to implement them and send a pull request.

**Comment by derickito** [comment]
The solution by @paperkettle works like a charm

**Comment by Esqarrouth** [comment]
Feel free to send a pull request

**Comment by Esqarrouth** [comment]
Fixed this in here:
https://github.com/goktugyil/EZSwipeController/commit/18427b8500d856c84db2880554fda34cfb9a09ee
