### ISSUE TITLE
Autolayout

### ISSUE THREAD

**Issue by lalamm** [goktugyil/EZSwipeController#20]
Hi!

How should I use this with autolayout?

I've tried to pin both to edges and/or to top/bottom layout guides for my viewcontroller but it's view is still outside the window. An example would be great!

Thanks again

**Comment by Esqarrouth** [comment]
Hello

http://stackoverflow.com/questions/tagged/ezswipecontroller

I personally do not use autolayout for this but you can ask your question here if you want to. If you solved the problem please send a pull request. Thanks!
