### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cristinaITdeveloper** [goktugyil/EZSwipeController#21]
After update to version 0.5, with xCode 7.2 I have this issue : 

![schermata 2016-04-13 alle 13 46 15](https://cloud.githubusercontent.com/assets/11472348/14492234/45a7da12-017e-11e6-84b8-79b177f8110c.png)

**Comment by cristinaITdeveloper** [comment]
Sorry, but I have now seen that the 0.5 version is for Swift 2.2

**Comment by Esqarrouth** [comment]
Yes, you can download and use 0.4 if you want to use an older version of Swift

**Comment by cristinaITdeveloper** [comment]
I use 0.4 version, but there is another problem. 
I have create a class that inherit from your controller and use it two times in my app in this way : 

```
let controller = ContainerViewController()
self.navigationController?.setViewControllers([controller], animated: true). 
```

When I use the first time, it works, but in the second time app crashes when I tap on bar button:

```
 *** Assertion failure in [UIPageViewController queuingScrollView:didEndManualScroll:toRevealView:direction:animated:didFinish:didComplete:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3512.30.14/UIPageViewController.m:2028
2016-04-13 15:24:47.848 EpicTour[3748:2248913] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'No view controller managing visible view  <UIView: 0x158c1f330; frame = (0 0; 375 667); autoresize = W+H; layer = <CALayer: 0x158c7a210>> 
```

How can I solve this problem?

**Comment by Esqarrouth** [comment]
For this type of questions please use, stackoverflow 'ezswipecontroller' tag
