### ISSUE TITLE
Navigation to view from my custom button.

### ISSUE THREAD

**Issue by minakshibh** [goktugyil/EZSwipeController#22]
I am able to implement your library in my project. but now i figure out one problem, I don't want navigation bar in my project and want to add custom button for navigating form one view to another just like we do by swiping e.g same as snapchat is doing on button clicks.

**Comment by Esqarrouth** [comment]
https://github.com/goktugyil/EZSwipeController#move-to-new-page
https://github.com/goktugyil/EZSwipeController#hide-navigation-bar
