### ISSUE TITLE
Not Working When launched in Landscape

### ISSUE THREAD

**Issue by BlackRussian** [goktugyil/EZSwipeController#24]
There is an issue when launched in landscape the pageViewController width is not streaching to full screen.

**Comment by Esqarrouth** [comment]
Yeah its not exactly for landscape. But should be compatible with some small changes

**Comment by dineshthangasamy** [comment]
Worked for me after i did something like this 
        pageViewController.view.frame = CGRect(x: 0, y: 0, width: UIScreen.mainScreen().bounds.width, height: UIScreen.mainScreen().bounds.height)

inside setupPageViewController and didRotateFromInterfaceOrientation. 

Should be a very easy fix even if u have to change the Y if u have a status bar.

**Comment by BlackRussian** [comment]
Thanks @dineshthangasamy worked like a charm. I also added the code to willRotateFromInterfaceOrientation. because i was having some weird transition.

@goktugyil should consider including in your build

**Comment by Esqarrouth** [comment]
Feel free to send a pull request

**Comment by dineshthangasamy** [comment]
I ended up doing this     public func setFrameForCurrentOrientation(){
        pageViewController.view.frame = CGRect(x: 0, y: 0, width: self.view.frame.size.width, height: self.view.frame.size.height)
    }

called this inside setupPageViewController and didRotateFromInterfaceOrientation - will open a PR soon

**Comment by JFKingsley** [comment]
Since we appear to have working orientation support in currently, I'm going to close this. That said, if any other issues with framing come up feel free to open a new issue.
