### ISSUE TITLE
add swipe up and down directions

### ISSUE THREAD

**Issue by xiaoao** [goktugyil/EZSwipeController#26]

**Comment by sheldonshi** [comment]
just change 

`pageViewController = UIPageViewController(transitionStyle: .Scroll, navigationOrientation: .Horizontal, options: nil)`
to

`pageViewController = UIPageViewController(transitionStyle: .Scroll, navigationOrientation: .Vertical, options: nil)`

**Comment by JFKingsley** [comment]
Since Sheldon appears to have solved your issue, i'm going to close this. If any other issues related to the library come up feel free to reopen.
