### ISSUE TITLE
Swift 3.0 Migration

### ISSUE THREAD

**Issue by katriciab** [goktugyil/EZSwipeController#29]
It would be great to have a Swift 3.0 migrated version.

**Comment by ignotusverum** [comment]
https://github.com/goktugyil/EZSwipeController/pull/30

**Comment by JFKingsley** [comment]
As of today, 0.6+ is now fully Swift 3 compatible!

**Comment by Esqarrouth** [comment]
You want me to push the latest version to cocoapods?

**Comment by JFKingsley** [comment]
If you can that would be great!

**Comment by Esqarrouth** [comment]
Done!
