### ISSUE TITLE
Get callback when a page is shown

### ISSUE THREAD

**Issue by imran20487** [goktugyil/EZSwipeController#3]
Hi,
I wanted to know if there is any callback which is called when a Page shown?
i.e when the first page is shown or for the next pages when you swipe.
So that I can reload the data for that ViewController.
I have a functionality where you can pinch to change the font of the text and I want it to be reflected in other view controllers dynamically when I swipe to next ViewController(page).

**Comment by Esqarrouth** [comment]
You can just call the viewdidappear method inside your viewcontrollers, that will work in most cases. Does that not work for your case?

**Comment by imran20487** [comment]
Yes, viewDidAppear() works. Thanks a lot.
