### ISSUE TITLE
Add page indicator

### ISSUE THREAD

**Issue by DamonChen117** [goktugyil/EZSwipeController#31]
Add page indicator as iOS main screen.

**Comment by Esqarrouth** [comment]
Didn't understand

**Comment by DamonChen117** [comment]
I mean UIPageControl, some small dots which indicate current page index.

**Comment by JFKingsley** [comment]
This should be entirely possible to implement using changedToPageIndex and a little VC magic. If you have any other issues related to the library, feel free to open a new one!
