### ISSUE TITLE
Crash when swaping and calling moveToPage at the same time.

### ISSUE THREAD

**Issue by DamonChen117** [goktugyil/EZSwipeController#32]
**\* Assertion failure in -[UIPageViewController queuingScrollView:didEndManualScroll:toRevealView:direction:animated:didFinish:didComplete:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3512.60.12/UIPageViewController.m:2028

**Comment by Esqarrouth** [comment]
We could add a little control for that I think, why are you calling them at the same time?

**Comment by DamonChen117** [comment]
Actually, It is the user doing it at the same time. There is a "Next" button on the UI, which calles "moveToPage". While the ui is moving one page to another page, click the "Next" button, app crashes. 
It's seems there is no event such as "moving started/ended", I cannot disable the button as a workaround.

**Comment by JFKingsley** [comment]
Is this still a current issue for you @DamonChen117? If so I'd be happy to take a closer look.

**Comment by DamonChen117** [comment]
Not really, I simply use UIScrollview to implement swipe and page.

**Comment by JFKingsley** [comment]
Okay, sure. Gonna close this for now then.
