### ISSUE TITLE
Problem with View Controllers

### ISSUE THREAD

**Issue by boshd** [goktugyil/EZSwipeController#33]
Any UI design or work I do directly on one of the view controllers in the storyboard doesn't show up when compiled. It seems that i cant do any work outside the actual .Swift file. what's going on?

```
extension INTNavigationController: EZSwipeControllerDataSource {
    func viewControllerData() -> [UIViewController] {

        let feedVC = FeedViewController()
        //feedVC.view.backgroundColor = UIColor.hotPink()
        let cameraVC = CameraViewController()
        //cameraVC.view.backgroundColor = UIColor.hotBlack()
        let profileVC = ProfileViewController()
        //profileVC.view.backgroundColor = UIColor.hotGreen()

        return [feedVC, cameraVC, profileVC]
    }
}
```

**Comment by Esqarrouth** [comment]
I don't work with storyboard so I can't test this. But its probably about init from storyboard method.

**Comment by chadpav** [comment]
Instead of init'ing your VC's directly you need to use the Storyboard to instantiate them.
e.g.
`storyboard().instantiateViewControllerWithIdentifier("FeedViewController")`

**Comment by JFKingsley** [comment]
Chad seems to have got it - If there are any more issues related to the Library directly feel free to open them!
