### ISSUE TITLE
Swift 3 version

### ISSUE THREAD

**Issue by Esqarrouth** [goktugyil/EZSwipeController#40]
There are multiple ones, which one would you guys like to have implemented here?

https://github.com/goktugyil/EZSwipeController/pull/36
https://github.com/goktugyil/EZSwipeController/pull/37
https://github.com/goktugyil/EZSwipeController/tree/swift-3

**Comment by Esqarrouth** [comment]
Also I'm no longer working on a project that is using this library, so its hard for me to maintain it. Would you like to maintain this @JFKingsley ?

**Comment by JFKingsley** [comment]
@goktugyil I'd be very happy to - I've found the project to be very useful in several of my recent projects.

**Comment by Esqarrouth** [comment]
I've added you as collaborator, good luck 😁

**Comment by JFKingsley** [comment]
Swift 3 support merged in!
