### ISSUE TITLE
UITableViewController?

### ISSUE THREAD

**Issue by HackShitUp** [goktugyil/EZSwipeController#46]
Can you initialize a UITableViewController in the ESwipeController?

**Comment by Esqarrouth** [comment]
yes, you can do any uiviewcontroller subclasses

**Comment by HackShitUp** [comment]
OMG YES, how would I be able to do that? My problem is a little unique though. So I have an array of objects (undetermined number, n) that is appended. Then, in viewDidLoad of the parent view controller for EZSwipeController, I loop through the objects to determine which view controller is appended. I got it to work, but it crashes because of something with the navigation bars.

**Comment by HackShitUp** [comment]
@goktugyil

**Comment by HackShitUp** [comment]
Oh fuck never mind, it works!!!
Thank you!
@goktugyil
