### ISSUE TITLE
Possible Retain Cycle 

### ISSUE THREAD

**Issue by AlexHmelevskiAG** [goktugyil/EZSwipeController#52]
Hi,correct me if i'm wrong but there is a possible retain cycle. Datasource is declared as a strong reference.
```swift
public var datasource: EZSwipeControllerDataSource?
```

From your example you expect users to do next:
``` swift 
class MySwipeVC: EZSwipeController {
    override func setupView() {
        datasource = self
    }
}
```

in this case it'll prevent the controller to be released. Maybe to avoid it probably it's better to define it as weak: 
```swift
public weak var datasource: EZSwipeControllerDataSource?
```

I noticed it in the one of the projects i'm working on. I can make a PR if it's needed

**Comment by Esqarrouth** [comment]
Yes please make a pr
