### ISSUE TITLE
Lock Swipe 

### ISSUE THREAD

**Issue by cafuni** [goktugyil/EZSwipeController#7]
I would to lock the swipe and allow only the forward through the button...

**Comment by Esqarrouth** [comment]
Hello, why do you want to lock the swipe? What is the use case?

**Comment by arvindravi** [comment]
Hey,
I have three VC's, VC2 being the homeVC, so a person can swipe left or right to go to VC1 or VC3. 
VC3 has a tableView.

On VC3, swiping right would take me to VC2, and swiping left would show there's nothing after it. I would like to disable this left swipe so I can implement tableView's cell editing options. Is this possible?

**Comment by Esqarrouth** [comment]
Yes is is possible. There is something that allows you to stop that last swiping by locking the last screen. But you need to search and find it in stackoverflow, I don't remember the name of it

**Comment by arvindravi** [comment]
@goktugyil Isn't that library specific? Could you point me in the right direction, if its not?

**Comment by gfpoliva** [comment]
Did anyone figure it out?

**Comment by Esqarrouth** [comment]
I've created a question for this in StackOverflow, hopefully someone answers there:

http://stackoverflow.com/questions/36447319/how-to-lock-swipe

By the way, in my app I didn't lock swipe but added an edit button at the top right corner and after clicking that button, tableviews cell editing options become available:

https://itunes.apple.com/tr/app/insta-archive-save-instagram/id1048488080?mt=8

**Comment by otymartin** [comment]
@goktugyil Any solution for this?

**Comment by otymartin** [comment]
@gabrieloliva @cafuni 
I did this
```swift 
extension MainViewController: EZSwipeControllerDataSource, UIScrollViewDelegate {

    func scrollViewDidScroll(_ scrollView: UIScrollView) {
        if self.currentVCIndex == 0 && scrollView.contentOffset.x < scrollView.bounds.size.width {
            scrollView.contentOffset = CGPoint(x: scrollView.bounds.size.width, y: 0)
        } else if self.currentVCIndex == self.swipeArray.count - 1 && scrollView.contentOffset.x > scrollView.bounds.size.width {
            scrollView.contentOffset = CGPoint(x: scrollView.bounds.size.width, y: 0)
        }
    }
    
    func scrollViewWillEndDragging(_ scrollView: UIScrollView, withVelocity velocity: CGPoint, targetContentOffset: UnsafeMutablePointer<CGPoint>) {
        if self.currentVCIndex == 0 && scrollView.contentOffset.x < scrollView.bounds.size.width {
            scrollView.contentOffset = CGPoint(x: scrollView.bounds.size.width, y: 0)
        } else if self.currentVCIndex == self.swipeArray.count - 1 && scrollView.contentOffset.x > scrollView.bounds.size.width {
            scrollView.contentOffset = CGPoint(x: scrollView.bounds.size.width, y: 0)
        }
    }
    
    func setAsScrollViewDelegate() {
        for view: UIView in pageViewController.view.subviews {
            if let scrollView = view as? UIScrollView {
                scrollView.delegate = self
            }
        }
    }
}
```

then in `viewDidLoad`
```swift
override func viewDidLoad() {
        super.viewDidLoad()
        self.setAsScrollViewDelegate()
    }
