### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AdventuresOfMar** [goktugyil/EZSwipeController#8]
Is there a way to start the navigation from a middle panel. Just like how tinder's main view is in the middle and you swipe to either the left side or right side to get to other views

**Comment by thellimist** [comment]
```
extension MySwipeVC: EZSwipeControllerDataSource {
    func indexOfStartingPage() -> Int {
        return 2 // EZSwipeController starts from 2nd, green page
    }
}
```

**Comment by AdventuresOfMar** [comment]
thanks so much @thellimist , one more quick question for you. Is there a way to have a middle icon image instead of text title?

**Comment by Esqarrouth** [comment]
Yeah,     

func navigationBarDataForPageIndex(index: Int) -> UINavigationBar 

in here, just like how the example puts images as buttons, you can put images instead of the string
