### ISSUE TITLE
Navigate to another controller with button action

### ISSUE THREAD

**Issue by itsjc** [goktugyil/EZSwipeController#9]
Hey guys,

I'm new to swift programming and wanted to know how to perform a swipe segue to another view controller using the same concept of the left button and right button except my buttons aren't part of a navigation controller.

I have tried presenting the view controller when the user clicks the button but that destroys the whole swipe setup for obvious reasons.

Please advise.

Thank you!

**Comment by Esqarrouth** [comment]
Have you tried stackoverflow?

**Comment by itsjc** [comment]
I'm not sure what to search as I thought it would be something unique to this library. I basically need a button to do the equivalent of swiping left or swiping right depending on button.

Thanks for your help man

**Comment by Esqarrouth** [comment]
You can just edit the library for the button to work like you intended. You need to go a little deep into the code but you can figure it out

**Comment by itsjc** [comment]
Mind pushing me a bit more into the right direction?

First week programming in Swift and I'm not as fluent as you might think I am.

**Comment by Esqarrouth** [comment]
You should just find some tutorials and implement what you see. I don't think you should try to do complex user experiences.

**Comment by itsjc** [comment]
Is that a joke, lol?

**Comment by Esqarrouth** [comment]
No, these stuff are complicated and buggy because Apple didn't make it very easy to make these interactions unfortunately
